
replicaCount: 1
positionSimulator:
   name: position-simulator
   namespace: default
   replicas: 2
   container: 
    image: richardchesterwood/k8s-fleetman-position-simulator:release2
positionTracker:      
  name: position-tracker
  namespace: default
  replicas: 1
  containers:
    image: richardchesterwood/k8s-fleetman-position-tracker:release3
  service:
    ports:
      name: http
      port: 8080
  type: ClusterIP
webapp:
  name: webapp
  namespace: default
  replicas: 1
  containers:
    image: richardchesterwood/k8s-fleetman-webapp-angular:release2
fleetmanWebapp:
  name: fleetman-webapp
  namespace: default
  ports:
    name: http
    port: 80
    targetPort: 80
  type: NodePort
apiGateway:
  name: api-gateway
  namespace: default
  replicas: 1
  containers:
    image: richardchesterwood/k8s-fleetman-api-gateway:release2
fleetmanApiGateway:
  name: fleetman-api-gateway
  namespace: default
  ports:
    name: http
    port: 8080
    targetPort: 8080
  type: NodePort
mongodb:
  name: mongodb
  namespace: default
  replicas: 1
  containers:
    image: mongo:3.6.5-jessie
  volumeMounts:
    name: mongo-persistent-storage
    mountPath: /data/db
  volumes:
    name: mongo-persistent-storage
    persistentVolumeClaim:
      claimName: mongo-pvc
fleetmanMongodb:
    name: fleetman-mongodb
    namespace: default
    ports:
        name: http
        port: 27017
        targetPort: 27017
    type: ClusterIP
queue:
  name: queue
  namespace: default
  replicas: 1
  containers:
    image: richardchesterwood/k8s-fleetman-queue:release2
fleetmanQueue:
  name: fleetman-queue
  namespace: default
  ports:
    name: http
    port: 80
    targetPort: 8161
    name2: endpoint
    port2: 61616   
  type: LoadBalancer
