 #API Gateway Platform
 #this works
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: default
spec:
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}
  replicas: {{ .Values.apiGateway.replicas }}
  template:
    metadata:
      namespace: default
      labels:
        app: {{ .Values.apiGateway.name }}
    spec:
      containers:
      - name: {{ .Values.apiGateway.name }}
        image: {{ .Values.apiGateway.containers.image }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
---
# The exposed port has to be 8080 because that is what the web app component is hardcoded to use
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fleetmanApiGateway.name }}
  namespace: default
spec:
  selector:
    app: {{ .Values.apiGateway.name }}
  ports:
    - name: {{ .Values.fleetmanApiGateway.ports.name }}
      port: {{ .Values.fleetmanApiGateway.ports.port }}
      targetPort: {{ .Values.fleetmanApiGateway.ports.targetPort }}
  type: {{ .Values.fleetmanApiGateway.type }}

